### ISSUE TITLE
CIFAR100 has different architecture from official implementation

### ISSUE THREAD

**Issue by zijian-hu** [kekmodel/FixMatch-pytorch#13]
In your implementation, WRN28-10 is used which has about 36M parameters.
Your model definition:
https://github.com/kekmodel/FixMatch-pytorch/blob/9044f2ef656fb135cf93c9b9f0fe1f6870ea266f/train.py#L165-L169

I used the following code to get the number of parameters
```python
wrn = build_wideresnet(depth=28, widen_factor=10, dropout=0, num_classes=100)

print(f"# params: {sum(p.numel() for p in wrn.parameters()):,}")
```
which gives the following output:
![Annotation 2020-09-09 005826](https://user-images.githubusercontent.com/16883354/92571171-a135c480-f237-11ea-9eb9-4f548fc13f21.png)

In the official TensorFlow implementation, a WRN with about 23M parameters is used for CIFAR100 (see below image).
![fixmatch num params - Copy](https://user-images.githubusercontent.com/16883354/92570605-f3c2b100-f236-11ea-9950-a7d359bf1530.png)

## Notes
The CLI args for the official code can be found in [this issue](https://github.com/google-research/fixmatch/issues/26).

**Comment by kekmodel** [comment]
fixed! thanks!
