### ISSUE TITLE
Accuracy curves

### ISSUE THREAD

**Issue by bkj** [kekmodel/FixMatch-pytorch#14]
Hi --

Are you able to share a screenshot of the accuracy curves (test accuracy vs epoch)?  I'm trying to reproduce your results, but it'd be helpful to make sure I'm on the right track since the models take so long to train.

Thanks!

**Comment by kekmodel** [comment]
https://tensorboard.dev/experiment/jVv8MvBPSv6m8S78437tdg/#scalars&_smoothingWeight=0
