### ISSUE TITLE
unlabeled data contain the labeled data?

### ISSUE THREAD

**Issue by yaojunr** [kekmodel/FixMatch-pytorch#18]
https://github.com/kekmodel/FixMatch-pytorch/blob/fe19cc734152b2488e3a5db23abc8df2acc5bdc6/dataset/cifar.py#L105-L106
In the code, the labeled data contain idx before label_per_class, but the unlabeld data contain all idx? Is this a bug?

**Comment by kekmodel** [comment]
https://github.com/kekmodel/FixMatch-pytorch/issues/10
