### ISSUE TITLE
What does the function `interleave` do?

### ISSUE THREAD

**Issue by charlesCXK** [kekmodel/FixMatch-pytorch#19]
Hi, nice work! When reading your code, I find a function named `interleave` in the `train.py`:
```python
def interleave(x, size):
    s = list(x.shape)
    return x.reshape([-1, size] + s[1:]).transpose(0, 1).reshape([-1] + s[1:])
```

Could you make some explanations about this function? I do not understand why we use this operation. Thank you!

**Comment by Z1Wu** [comment]
https://github.com/google-research/fixmatch/issues/20#issuecomment-613010277

**Comment by Z1Wu** [comment]
https://github.com/google-research/fixmatch/issues/20#issuecomment-613010277

**Comment by Z1Wu** [comment]
https://github.com/google-research/fixmatch/issues/20#issuecomment-613010277
In the official implementation of fixmatch, the author has mentioned about the purpose of interleave operation. But I am not sure Pytorch ddp module has same behavior as Tensorflow.

**Comment by charlesCXK** [comment]
@Z1Wu 
Thanks for your help! I have understood what the author claimed. It is fortunate that the situation does not exist in PyTorch DDP, where each GPU will have both labeled and unlabeled data.

Apart from that, I find this operation seems to do nothing in PyTorch. I test the function using the following code:
```python
import torch

def interleave(x, size):
    s = list(x.shape)
    return x.reshape([-1, size] + s[1:]).transpose(0, 1).reshape([-1] + s[1:])

b = 3
x = torch.ones(b, 4, 5)
cnt = 1
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        for k in range(x.shape[2]):
            x[i,j,k] = cnt
            cnt += 1
print(x)
y = interleave(x, b)
print(y)
```
The output shows x and y are just the same.

**Comment by kekmodel** [comment]
The size value must be a divisor of b less than b.

**Comment by charlesCXK** [comment]
I know, thanks!
