### ISSUE TITLE
is there performance difference between RandAugmentMC and RandAugmentPC

### ISSUE THREAD

**Issue by valencebond** [kekmodel/FixMatch-pytorch#3]
what's the point of this code in RandAugmentPC
```
prob = np.random.uniform(0.2, 0.8)
            if random.random() + prob >= 1:
```

**Comment by kekmodel** [comment]
https://github.com/tensorflow/tpu/blob/ad7869098ef9db5b632375366e96c2b6398a1ae5/models/official/efficientnet/autoaugment.py#L564
