### ISSUE TITLE
Have you  tried SVHN dataset?

### ISSUE THREAD

**Issue by fiona-lxd** [kekmodel/FixMatch-pytorch#30]

**Comment by kekmodel** [comment]
Not yet. `SVHN` needs to change to `RandAugment`.

**Comment by fiona-lxd** [comment]
> Not yet. `SVHN` needs to change to `RandAugment`.

What needs to get changed?

**Comment by louis2889184** [comment]
Hi @kekmodel, do you know what have to be changed in `RandAugment`? In the official implementation, I only see they remove the `HorizontalFlip` for SVHN.

**Comment by kekmodel** [comment]
@

> Hi @kekmodel, do you know what have to be changed in `RandAugment`? In the official implementation, I only see they remove the `HorizontalFlip` for SVHN.

Check out the paper's appendix c2.
