### ISSUE TITLE
RandAugment Implementation

### ISSUE THREAD

**Issue by psellcam** [kekmodel/FixMatch-pytorch#33]
Hello I am very curious about this part of the randaugment implementation  in the RandAugmentMC class

 if random.random() < 0.5:
                img = op(img, v=v, max_v=max_v, bias=bias)

If I am understanding this right, for RandaugmentMC with n=2 there is a 25% chance of no randaugment operator, 50% chance of one randaugment operator and a 25% of two randaugment operators occurring for a given image. 

Is this what you found in the fixmatch implementation as this isn't what I understood the paper to do?

**Comment by zhjscut** [comment]
In official implementation, I find this:
![image](https://user-images.githubusercontent.com/32974196/120620305-6e032780-c48f-11eb-8e87-b53cd3609e5d.png)
and in config file there is:
![image](https://user-images.githubusercontent.com/32974196/120620358-7bb8ad00-c48f-11eb-9a5f-edd28081c66a.png)
So I think `if random.random() < 0.5:` is a correct reimplementation.

**Comment by psellcam** [comment]
Thank you for finding,

This is very surprising as far I can tell there is no mention of this in the paper at all

**Comment by inigoval** [comment]
I had the same thoughts, very strange that this isn't mentioned at all in the paper.
