### ISSUE TITLE
set_epoch with DistributedSampler

### ISSUE THREAD

**Issue by TonyLianLong** [kekmodel/FixMatch-pytorch#34]
Hello @kekmodel, thanks for the amazing implementation.

According to the documentation https://pytorch.org/docs/stable/data.html, if DistributedSampler is used, we need to call `set_epoch` function before each epoch. However, I did not find `set_epoch` in train.py. Should you add that?

**Comment by kekmodel** [comment]
You are right. If you use `DistributedSampler`, you have to add `set_epoch`. Thank you!
