### ISSUE TITLE
The RandAugment Implementation Is Wrong

### ISSUE THREAD

**Issue by psellcam** [kekmodel/FixMatch-pytorch#39]
https://github.com/google-research/fixmatch/issues/65

As confirmed by the collaborator of the official implementation the randaugment function should be applied all the time not 50 percent of the time.

The only 50% chance from the original paper refers to the flips etc of weak augmentation only and definitely not the strong augmentation methods

This could explain why this repository does better than the original paper but it isn't what the original paper did. 

For those who want the true performance of the original fixmatch paper you need to delete 

>  if random.random() < 0.5:

From the https://github.com/kekmodel/FixMatch-pytorch/blob/master/dataset/randaugment.py file

**Comment by 07Agarg** [comment]
Hi @psellcam , thanks for pointing out the issue. 
I believe then this ``` if random.random() < 0.5: ``` is removed from the class ``` RandAugmentPC ``` and the class ``` RandAugmentMC ```. 

Let me know if I understand this correctly. Thanks again.

**Comment by psellcam** [comment]
Yes exactly!!

**Comment by kekmodel** [comment]
https://github.com/kekmodel/FixMatch-pytorch/issues/33

**Comment by kekmodel** [comment]
https://github.com/google-research/fixmatch/blob/d4985a158065947dba803e626ee9a6721709c570/third_party/auto_augment/augmentations.py#L213
and
https://github.com/google-research/fixmatch/blob/d4985a158065947dba803e626ee9a6721709c570/libml/augment.py#L198
