### ISSUE TITLE
Wrong use of AverageMeter

### ISSUE THREAD

**Issue by huberl** [kekmodel/FixMatch-pytorch#40]
Shouldn't the [AverageMeters ](https://github.com/kekmodel/FixMatch-pytorch/blob/master/train.py#L306-L311)in train.py be reseted after each epoch? 

The [original ImageNet example](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L265) does this.

**Comment by kekmodel** [comment]
Thanks!
