### ISSUE TITLE
v divided by 2 problem in Cutout

### ISSUE THREAD

**Issue by Fordacre** [kekmodel/FixMatch-pytorch#44]
Hi Kim, 
I find that in https://github.com/kekmodel/FixMatch-pytorch/blob/f54946074fba383e28320d8f50b627eabd0c7e3c/dataset/randaugment.py#L53 `v` isn't divided by 2. But in https://github.com/kekmodel/FixMatch-pytorch/blob/f54946074fba383e28320d8f50b627eabd0c7e3c/dataset/randaugment.py#L51 `v` is divided by 2. Is it a mistake, or there are some foundations?

**Comment by kekmodel** [comment]
https://github.com/ildoonet/pytorch-randaugment/blob/48b8f509c4bbda93bbe733d98b3fd052b6e4c8ae/RandAugment/augmentations.py#L127
I referred to this code. If you calculate it yourself, this equation is correct.
