### ISSUE TITLE
cos learing rate

### ISSUE THREAD

**Issue by YUE-FAN** [kekmodel/FixMatch-pytorch#6]
Hi, 

It seems the last line in `get_cosine_schedule_with_warmup` funtion should be:
`return max(0., (math.cos(math.pi * num_cycles * no_progress) + 1 ) * 0.5)`

But I am not sure about this, correct me if I am wrong, thanks

**Comment by kekmodel** [comment]
Cosine annealing of code is not the way it was used in general. I implemented a new method in FixMatch paper.

**Comment by YUE-FAN** [comment]
Oh, I see. Yours is indeed correct.
